create table `EL_TABLE` (
       `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       `chain_name` varchar(32) NOT NULL,
       `el_data` varchar(1024) NOT NULL,
       PRIMARY KEY (`id`)
) ;